pr:
  - main
  - releases/*
 
trigger:
- main

stages:
- stage: ServiceNowDev
  displayName: 'Deploy to Dev'
  jobs:
  - job: deploy_infratsructure
    displayName: Deploy to Dev
    strategy:
      matrix:
        jdk10_linux:
          imageName: "ubuntu-latest"
          jdkVersion: "1.10"
        jdk11_windows:
          imageName: "windows-latest"
          jdkVersion: "1.11"
      maxParallel: 1
    pool:  
      vmImage: $(imageName)
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: "pom.xml"
          mavenOptions: "-Xmx3072m"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: $(jdkVersion)
          jdkArchitectureOption: "x64"
          publishJUnitResults: true
          testResultsFiles: "**/TEST-*.xml"
          goals: "package"
  - job: 'ServiceNowChangeRecord'
    displayName: 'Trigger Change Record through DevOps'
    dependsOn:
    - deploy_infratsructure
    condition: succeeded()
    pool:
      name: Server
    steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
          changeRequestDetails: |
            {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "abel.tuter"
                  },
                  "start_date": "2021-01-05 08:00:00",
                  "end_date": "2021-01-08 08:00:00"
                }
              }
