trigger: none

pool: 
 vmImageName: 'windows-latest'

stages:
  - stage: Demo_run
    jobs:
      - job: now_change
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  "setCloseCode" : true,
                  "autoCloseChange" : true,
                  "attributes": {
                    "requested_by": {
                      "name": "Abel Tuter"
                    },
                    "start_date": "2025-01-05 08:00:00",
                    "end_date": "2025-01-08 08:00:00",
                    "template": "2e99ac42c319121055225f73e4013151"
                  }
                }
