trigger: none

pool: 
 vmImageName: 'windows-latest'

stages:
  - stage: Demo_run
    jobs:
      - job: now_change
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  "setCloseCode" : true,
                  "autoCloseChange" : true,
                  "attributes": {
                    "requested_by": {
                      "name": "Abel Tuter"
                    },
                    "assignment_group": {
                      "name": "Analytics Settings Managers"
                    },
                    "start_date": "2025-01-05 08:00:00",
                    "end_date": "2025-01-08 08:00:00",
                    "priority": 3,
                    "short_description": "Testing DevOps SD",
                    "description": "Testing DevOps desc",
                    "work_notes": "Testing DevOps worknotes",
                    "u_department": "Testing Department",
                    "cab_required": "true",
                  }
                }