trigger: none

pool: 
 vmImageName: 'windows-latest'

stages:
  - stage: Demo_run
    jobs:
      - job: now_change
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  
                    "start_date": "2021-01-05 08:00:00",
                    "end_date": "2021-01-08 08:00:00"
                
                }