trigger: none

pool: 
 vmImageName: 'windows-latest'

stages:
  - stage: Demo_run
    jobs:
      - job: now_change
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'