trigger: none

pool: 
 vmImageName: 'windows-latest'

stages:
  - stage: Demo_run
    jobs:
      - job: now_change
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev218664-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  
                    "start_date": "2024-10-20 08:00:00",
                    "end_date": "2024-11-20 08:00:00",
                    "priority": 3,
                    "comments": "Testing Azure DevOps"
                
                }