trigger: none

pool:
  vmImage: ubuntu-latest
 
stages:
  - stage: Build
    jobs: 
      - job: Build
        steps:
          - script: echo "This is the planning phase of the request."


  - stage: registerArtifact
    jobs:
     - job: Register_Artifact
       pool: server
       steps:
#- script: echo "This is the register artifact phase of the request"
         - task: ServiceNow-DevOps-Server-Artifact-Registration@1
           inputs:
             connectedServiceName: 'dev183223-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
             artifactRegistrationPayload: |
               {
                  "artifacts": [
                     {
                        "name": "app-devops-cicd.jar",
                        "version": "1.$(build.buildId)",
                        "semanticVersion": "1.$(build.buildId).0",
                        "repositoryName": "npj96/NJ-DemoRepo"
                     }
                  ],
                  "pipelineName": "$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber": "$(build.buildId)",
                  "stageName": "$(system.jobDisplayName)",
                "attemptNumber": "$(system.jobAttempt)",
                  "branchName": "$(build.sourceBranchName)"
               }
             artifactToolIdExists: true

  - stage: registerPackage
    jobs:
      - job: Register_Package
        pool: server
        steps:
#- script: echo "This is the register package phase of the request"
        - task: ServiceNow-DevOps-Server-Package-Registration@1
          inputs:
            connectedServiceName: 'dev183223-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            packageRegistrationPayload: |
              {
                  "name": "app-devops-change-velocity-cicd.war",
                  "artifacts": [
                  {
                      "name": "app-devops-cicd.jar",
                      "repositoryName": "npj96/NJ-DemoRepo",
                      "version": "1.$(build.buildId)",
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(system.jobDisplayName)",
                "attemptNumber":"$(system.jobAttempt)",
                    "branchName":"$(build.sourceBranchName)"
                  }],
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
               "attemptNumber":"$(system.jobAttempt)",
                  "branchName":"$(build.sourceBranchName)"
              }
            artifactToolIdExists: true
        
  - stage: Prod    
    jobs:
     - job: Final_Deployment
       pool: server
       steps:
#- script: echo This is the production deployement phase!
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev183223-NJ- DevOps Practice-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  "setCloseCode" : true,
                  "autoCloseChange" : true,
                  "attributes": {
                    "requested_by": {
                      "name": "Abel Tuter"
                    },
                    "assignment_group": {
                      "name": "Analytics Settings Managers"
                    },
                    "start_date": "2024-11-05 08:00:00",
                    "end_date": "2025-01-08 08:00:00",
                    "priority": 3,
                    "cab_required": "yes"
                  }
                }   
                
